//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdc_Api.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conta()
        {
            this.Lancamentoes = new HashSet<Lancamento>();
        }
    
        public string NumeroConta { get; set; }
        public string Tipo { get; set; }
        public double Saldo { get; set; }
        public int IdPacote { get; set; }
        public string IdAgencia { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Pacote Pacote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lancamento> Lancamentoes { get; set; }
    }
}
