//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdc_Api.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lancamento
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public double Valor { get; set; }
        public System.DateTime Data { get; set; }
        public string IdNumeroConta { get; set; }
        public string IdCpf { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Conta Conta { get; set; }
    }
}
